language: node_js
node_js: stable
cache:
    apt: true
    directories: 
        - node_modules
before_script:
    cd /home/travis/build/hellojackhui/hui-ui/
    npm install
script:
    npm run start
